# Generated by Django 3.1.1 on 2021-04-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneWebApp', '0003_auto_20210403_0754'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('rID', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='saved_recipes',
            field=models.ManyToManyField(to='CapstoneWebApp.Recipe'),
        ),
    ]
