# Generated by Django 3.1.1 on 2021-04-03 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneWebApp', '0004_auto_20210403_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('iID', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('recipes', models.ManyToManyField(to='CapstoneWebApp.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('pricePer', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('purchaseDate', models.DateTimeField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CapstoneWebApp.ingredient')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CapstoneWebApp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CapstoneWebApp.profile')),
            ],
        ),
    ]
