# Generated by Django 3.1.1 on 2021-04-03 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneWebApp', '0005_fridge_fridgeitem_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fridge',
        ),
    ]
