# Generated by Django 3.1.1 on 2021-04-03 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneWebApp', '0006_delete_fridge'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='iID',
            new_name='i_ID',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='rID',
            new_name='r_ID',
        ),
        migrations.RemoveField(
            model_name='fridgeitem',
            name='pricePer',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='quantity',
            field=models.IntegerField(max_length=4),
        ),
        migrations.CreateModel(
            name='QuantityPerRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CapstoneWebApp.recipe')),
            ],
        ),
    ]
