# Generated by Django 3.1.7 on 2021-04-05 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneWebApp', '0007_auto_20210403_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantityperrecipe',
            name='ingredient',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='CapstoneWebApp.ingredient'),
            preserve_default=False,
        ),
    ]
