# Generated by Django 3.1.7 on 2021-04-22 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneWebApp', '0008_quantityperrecipe_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
    ]
