# Generated by Django 3.1.7 on 2021-05-22 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneWebApp', '0009_remove_recipe_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
