# Generated by Django 3.1.7 on 2021-05-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneWebApp', '0011_delete_fridgeitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intolerance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='dislikedFoods',
            field=models.ManyToManyField(blank=True, null=True, to='CapstoneWebApp.Ingredient'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='saved_recipes',
            field=models.ManyToManyField(blank=True, null=True, to='CapstoneWebApp.Recipe'),
        ),
        migrations.DeleteModel(
            name='QuantityPerRecipe',
        ),
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='CapstoneWebApp.diet'),
        ),
        migrations.AddField(
            model_name='profile',
            name='intolerances',
            field=models.ManyToManyField(blank=True, null=True, to='CapstoneWebApp.Intolerance'),
        ),
    ]
