# Generated by Django 3.1.7 on 2021-05-22 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CapstoneWebApp', '0012_auto_20210522_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='intolerance',
            name='description',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
